import React, { useState } from 'react';
import { 
  FileSearch, CheckCircle2, AlertTriangle, HelpCircle, 
  ShieldCheck, Layers, Link as LinkIcon 
} from 'lucide-react';
import { FECGauge } from '../components/common/FECGauge';
import { ScoreExplainModal } from '../components/common/ScoreExplainModal';
import type { FECResult } from '../types';

interface EvidenceForensicsProps {
  fecData: FECResult | null;
}

export const EvidenceForensics: React.FC<EvidenceForensicsProps> = ({ fecData }) => {
  const [isModalOpen, setIsModalOpen] = useState(false);

  if (!fecData) return <div className="p-6 text-slate-400">Loading evidence forensics score...</div>;

  return (
    <div className="p-6 space-y-6 max-w-7xl mx-auto">
      {/* Top Banner & FEC Gauge */}
      <div className="bg-[#111827] border border-[#1e293b] rounded-xl p-6 flex flex-col md:flex-row items-center justify-between gap-6">
        <div className="space-y-3">
          <div className="flex items-center gap-2 text-indigo-400 font-mono text-xs font-semibold">
            <FileSearch className="w-4 h-4" /> FORENSIC EVIDENCE SUFFICIENCY (FEC)
          </div>
          <h1 className="text-2xl font-bold text-slate-100">FORENSIC EVIDENCE COVERAGE ENGINE</h1>
          <p className="text-xs text-slate-400 max-w-xl">
            Measures whether sufficient telemetry exists across required evidence domains to conclusively reconstruct the incident. Score is 100% mathematical and deterministic (never generated by an LLM).
          </p>

          <button
            onClick={() => setIsModalOpen(true)}
            className="px-4 py-2 rounded-lg bg-indigo-600/20 border border-indigo-500/40 text-indigo-300 hover:bg-indigo-600/30 text-xs font-semibold flex items-center gap-2 transition-colors"
          >
            <HelpCircle className="w-4 h-4 text-indigo-400" /> Why This Score? (Mathematical Proof)
          </button>
        </div>

        <div className="bg-[#0b0f19] border border-[#1e293b] rounded-2xl p-4 shrink-0">
          <FECGauge score={fecData.overall_fec} size={160} label="Current Baseline FEC" />
        </div>
      </div>

      {/* Grid: Domain Breakdown & Stage Confidence */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Domain Breakdown Table */}
        <div className="bg-[#111827] border border-[#1e293b] rounded-xl p-5 space-y-4">
          <h3 className="font-bold text-slate-100 text-sm tracking-wide flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-indigo-400" /> EVIDENCE DOMAIN AUDIT MATRIX
          </h3>

          <div className="border border-[#1e293b] rounded-lg overflow-hidden font-mono text-xs">
            <table className="w-full text-left border-collapse">
              <thead className="bg-[#161b22] text-slate-400 text-[11px] border-b border-[#1e293b]">
                <tr>
                  <th className="p-3">Evidence Domain</th>
                  <th className="p-3">Weight</th>
                  <th className="p-3">Status</th>
                  <th className="p-3 text-right">Availability</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-[#1e293b]">
                {Object.entries(fecData.domain_status).map(([domain, status]) => (
                  <tr key={domain} className={!status.available ? 'bg-rose-500/5' : ''}>
                    <td className="p-3 font-semibold text-slate-200">{domain}</td>
                    <td className="p-3 text-slate-400">{(status.weight * 100).toFixed(0)}%</td>
                    <td className="p-3">
                      {status.available ? (
                        <span className="text-emerald-400 font-semibold flex items-center gap-1">
                          <CheckCircle2 className="w-3.5 h-3.5" /> Verified
                        </span>
                      ) : (
                        <span className="text-rose-400 font-bold flex items-center gap-1">
                          <AlertTriangle className="w-3.5 h-3.5" /> Missing Telemetry
                        </span>
                      )}
                    </td>
                    <td className="p-3 text-right font-bold">
                      {status.available ? (
                        <span className="text-emerald-400">100%</span>
                      ) : (
                        <span className="text-rose-400">0%</span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Stage-wise Reconstruction Confidence */}
        <div className="bg-[#111827] border border-[#1e293b] rounded-xl p-5 space-y-4">
          <h3 className="font-bold text-slate-100 text-sm tracking-wide flex items-center gap-2">
            <Layers className="w-4 h-4 text-indigo-400" /> STAGE-WISE RECONSTRUCTION CONFIDENCE
          </h3>
          <p className="text-xs text-slate-400">
            Identifies weak stages in the attack chain caused by missing evidence telemetry.
          </p>

          <div className="space-y-4 pt-2 font-mono text-xs">
            {Object.entries(fecData.stages).map(([stage, score]) => (
              <div key={stage} className="space-y-1.5">
                <div className="flex justify-between text-slate-200">
                  <span className="font-semibold">{stage}</span>
                  <span className={`font-bold ${score >= 80 ? 'text-emerald-400' : score >= 60 ? 'text-amber-400' : 'text-rose-400'}`}>
                    {score}%
                  </span>
                </div>
                <div className="w-full bg-[#161b22] h-2 rounded-full overflow-hidden border border-[#1e293b]">
                  <div
                    className={`h-full rounded-full transition-all duration-500 ${
                      score >= 80 ? 'bg-emerald-500' : score >= 60 ? 'bg-amber-500' : 'bg-rose-500'
                    }`}
                    style={{ width: `${score}%` }}
                  ></div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>

      {/* Evidence Provenance Trace */}
      <div className="bg-[#111827] border border-[#1e293b] rounded-xl p-5 space-y-4">
        <h3 className="font-bold text-slate-100 text-sm tracking-wide flex items-center gap-2">
          <LinkIcon className="w-4 h-4 text-indigo-400" /> EVIDENCE PROVENANCE & FORENSIC AUDIT TRAIL
        </h3>
        <p className="text-xs text-slate-400">
          Every conclusion is directly linked back to supporting raw telemetry event IDs for transparent judicial auditing.
        </p>

        <div className="border border-[#1e293b] rounded-lg overflow-hidden font-mono text-xs">
          <table className="w-full text-left border-collapse">
            <thead className="bg-[#161b22] text-slate-400 text-[11px] border-b border-[#1e293b]">
              <tr>
                <th className="p-3">Forensic Conclusion</th>
                <th className="p-3">Supporting Events</th>
                <th className="p-3 text-right">Evidence Strength</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-[#1e293b]">
              {fecData.provenance_trace.map((item, idx) => (
                <tr key={idx} className={item.strength.includes('MISSING') ? 'bg-rose-500/5' : ''}>
                  <td className="p-3 font-semibold text-slate-200">{item.conclusion}</td>
                  <td className="p-3 text-indigo-400 font-bold">
                    {item.supported_by.length > 0 ? item.supported_by.join(', ') : 'None (Telemetry Absent)'}
                  </td>
                  <td className="p-3 text-right font-bold">
                    <span className={item.strength === 'HIGH' ? 'text-emerald-400' : 'text-rose-400'}>
                      {item.strength}
                    </span>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Modal */}
      <ScoreExplainModal
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        fecData={fecData}
      />
    </div>
  );
};
